"""MPGCF baseline configuration for one-click PyCharm execution."""
from pathlib import Path

BASELINE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASELINE_DIR.parent.parent
WORKSPACE_DIR = PROJECT_ROOT / "outputs" / "care" / "split2026" / "seed17"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "baselines" / "mpgcf" / "split2026"

SPLIT_SEED = 2026
TRAIN_SEEDS = (17, 29, 43, 71, 101)
CUTOFFS = (5, 10, 15, 20)

# Defaults published in the official MPGCF repository.
EMBEDDING_DIM = 256
PROPAGATION_LAYERS = 3
LEARNING_RATE = 1e-4
STRUCTURE_LOSS_WEIGHT = 1e-5
SEMANTIC_LOSS_WEIGHT = 1e-3
REGULARIZATION_WEIGHT = 1e-4
STRUCTURE_TEMPERATURE = 0.1
SEMANTIC_TEMPERATURE = 0.1
STRUCTURE_USER_WEIGHT = 0.3
STRUCTURE_ITEM_WEIGHT = 0.7
SEMANTIC_USER_WEIGHT = 1e-3
SEMANTIC_ITEM_WEIGHT = 1e-3
ACCURACY_FUSION_ALPHA = 0.7
NON_ACCURACY_EXPONENT = 1.25
TEXT_FUSION_WEIGHT = 0.5
BATCH_SIZE = 4096
MAX_EPOCHS = 300
EVAL_EVERY = 10
PATIENCE = 8
DEVICE = "cuda"
